[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["app", "tests", "utils"]

[tool.autoflake]
in-place = true
remove-all-unused-imports = true
expand-star-imports = true
remove-duplicate-keys = true
remove-unused-variables = true

[tool.flake8]
max-complexity = 10
statistics = true
max-line-length = 120

[tool.mypy]
plugins = ["pydantic.mypy"]
